fos_ck_editor:
    base_path: build/ckeditor
    js_path: build/ckeditor/ckeditor.js
    default_config: entity_form_config
    configs:
        entity_form_config:
            toolbar: 'full'
            uiColor: '#ffffff'
            image:
                resizeUnit: '%'
                resizeOptions:
                    handleStyles: {
                        backgroundColor: '#000',
                        border: '1px solid #ccc'
                    }
                imageCaption: true
                imageStyle: {
                    options: [
                        'alignLeft', 'alignCenter', 'alignRight'
                    ]
                }
            removePlugins: 'image'
            extraPlugins: [image2, codesnippet]
    toolbars:
        items:
            full.about: [ 'CodeSnippet' ]
