framework:
    html_sanitizer:
        sanitizers:
            app.post_sanitizer:
                allow_safe_elements: true
                allow_attributes:
                    style: '*'
                    class: '*'
