version: '3.8'

services:
    database:
        container_name: database
        image: mariadb:10.6
        env_file:
            - .env
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - mariadb_data:/var/lib/mysql

    php:
        container_name: php
        build:
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/Blog
            - /var/www/Blog/vendor
            - /var/www/Blog/node_modules
        depends_on:
            - database

    node:
        container_name: node
        build:
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - ./:/var/www/Blog
            - /var/www/Blog/vendor
            - /var/www/Blog/node_modules

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./public:/var/www/Blog/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        depends_on:
            - database
            - php
            - node

volumes:
    mariadb_data:
