version: '3.8'

services:
    database:
        container_name: mariadb
        image: mariadb:10.11.2
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - default

    php:
        container_name: php
        build:
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/Blog
        networks:
            - default
        depends_on:
            - database

    node:
        container_name: node
        build:
            dockerfile: ./docker/node/Dockerfile
        volumes:
            - ./:/var/www/Blog
        networks:
            - default

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - '8080:80'
        volumes:
            - ./public:/var/www/Blog/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        depends_on:
            - database
            - php
            - node

networks:
    default:

volumes:
    mariadb_data:
