version: "3.9"

services:
    database:
        container_name: blog-mariadb
        image: mariadb:10.11.2
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - blog

    php:
        container_name: blog-php
        build:
            dockerfile: ./docker/php/Dockerfile.prod
        restart: always
        environment:
            - APP_ENV=prod
        volumes:
            - symfony_data:/var/www/html
        networks:
            - blog
        depends_on:
            - database

    nginx:
        container_name: blog-nginx
        image: nginx:stable-alpine
        restart: always
        expose:
            - 80
        environment:
            - VIRTUAL_HOST=blog.albertv.dev
            - LETSENCRYPT_HOST=blog.albertv.dev
        volumes:
            - symfony_data:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
            - blog
        depends_on:
            - php

networks:
    default:
        name: nginx-proxy
        external: true
    blog:

volumes:
    symfony_data:
    mariadb_data:
