version: "3.9"

services:
    database:
        container_name: mariadb
        image: mariadb:10.11.2
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
        volumes:
            - mariadb_data:/var/lib/mysql
        networks:
            - default

    php:
        container_name: php
        build:
            dockerfile: ./docker/php/Dockerfile.dev
        volumes:
            - ./:/var/www/html/Blog
        networks:
            - default
        depends_on:
            - database

    node:
        container_name: node
        build:
            dockerfile: ./docker/node/Dockerfile.dev
        volumes:
            - ./:/var/www/html/Blog
        networks:
            - default

    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
            - 8080:80
        volumes:
            - ./public:/var/www/html/Blog/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        depends_on:
            - php

networks:
    default:

volumes:
    mariadb_data:
